### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by Anil-bohorya** [didinj/mean-stack-angular5-crud#6]
Working fine when redirected from 'http://localhost:4000/books'  to  'http://localhost:4000/book-details/5a504218db1db3121100c215' by clicking show-details

But when refresh 'http://localhost:4000/book-details/5a504218db1db3121100c215' page disappear and error shown:

Error: No default engine was specified and no extension was provided.
    at new View (/Users/Username/Downloads/mean5/mean-stack-angular5-crud/node_modules/express/lib/view.js:61:11)
    at Function.render (/Users/Username/Downloads/mean5/mean-stack-angular5-crud/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/Users/Username/Downloads/mean5/mean-stack-angular5-crud/node_modules/express/lib/response.js:1008:7)

i tried to console inside  book-detail.component.ts

ngOnInit() {
    console.log(this.route.snapshot.params['id']);
    this.getBookDetail(this.route.snapshot.params['id']);
  }

but nothing in shown in console.

Please help.

**Comment by vickrant** [comment]
add the following line too
app.use('', book);
